sudo: required
services: 
  - docker

before_install
  - docker build -t 3323/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true 3323/react-test npm test

after_success:
  - docker build -t 3323/multi-client ./client
  - docker build -t 3323/multi-nginx ./nginx
  - docker build -t 3323/multi-server ./server
  - docker build -t 3323/multi-worker ./worker

  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push 3323/multi-client
  - docker push 3323/multi-nginx   
  - docker push 3323/multi-server
  - docker push 3323/multi-worker